set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER mpifccpx)
set(CMAKE_Fortran_COMPILER mpifrtpx)
set(CMAKE_CXX_COMPILER mpiFCCpx)
set(CXX_TOOLCHAINFLAGS "-Kfast,-Kparallel,openmp,optmsg=2 --linkfortran")
set(F_TOOLCHAINFLAGS "-Kfast,-Kparallel,openmp,optmsg=2 -Cpp")
#add_definitions(-DNOBLOCK)
set(PYTHON_INCLUDE_PATH "/home/ra000010/a03363/include/python2.7")
#set(PYTHON_LIBRARIES "/home/ra000010/a03363/lib/python2.7/")
#set(CXX_TOOLCHAINFLAGS "--linkfortran")
#set(F_TOOLCHAINFLAGS "-Cpp -DPURE=")
